files:
  - source: /app/src/**/res/values/strings*.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        id: in
  - source: /app/src/**/res.lang/values/strings*.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        id: in
  - source: /metadata/en-US/*.txt
    ignore:
      - video.txt
    translation: /metadata/%locale%/%original_file_name%
  - source: /metadata/en-US/changelogs/*.txt
    ignore:
      - '/metadata/en-US/changelogs/[123]?.txt'
      - /metadata/en-US/changelogs/?.txt
      - '/metadata/en-US/changelogs/1020[45]??.txt'
    translation: /metadata/%locale%/changelogs/%original_file_name%
  - source: /metadata/en-US/GooglePlayStore
    translation: /metadata/%locale%/GooglePlayStore/%original_file_name%
